name: webinar
description: italent project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

  intl: ^0.19.0
  flutter_svg: ^2.0.7
  provider: ^6.1.1
  dio: ^5.2.1+1
  persian_number_utility: ^1.1.3
  file_picker: ^8.0.7
  shared_preferences: ^2.1.2
  loading_indicator: ^3.1.0
  get_it: ^7.6.0
  flutter_advanced_drawer: ^1.3.5
  flutter_rating_bar: ^4.0.1
  google_sign_in: ^6.2.1
  url_launcher: ^6.1.12
  add_2_calendar: ^3.0.1
  http: ^1.1.2
  flutter_widget_from_html: ^0.15.0
  video_player: ^2.8.6
  share_plus: ^9.0.0
  permission_handler: ^11.1.0
  path_provider: ^2.1.0
  open_file: ^3.3.0
  flutter_image_compress: ^2.0.4
  image_picker: ^1.0.7
  flutter_slidable: ^3.0.0
  webview_flutter: ^4.4.2
  pod_player: ^0.2.2
  flutter_tts: ^4.0.2
  table_calendar: ^3.0.9
  confetti: ^0.7.0
  animated_flip_counter: ^0.3.4
  fl_chart: ^0.68.0
  syncfusion_flutter_pdfviewer: ^24.2.8
  timezone: ^0.9.2
  flutter_inappwebview: ^6.0.0
  lottie: ^3.0.0
  shimmer: ^3.0.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.3
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.8
  flutter_pdfview: ^1.3.4
  flutter_barcode_scanner: ^2.0.0
  uni_links: ^0.5.1
  firebase_auth: ^4.20.0
  flutter_secure_storage: ^9.2.2
  google_nav_bar: ^5.0.7
  iconly: ^1.0.1
  flutter_iconly: ^1.0.2
  open_file_macos: ^0.1.0
  screen_protector: ^1.4.2+1
  flutter_spinkit: ^5.2.1
  win32: ^5.5.4
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.8.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
dependency_overrides:
  flutter_inappwebview_android:
    git:
      url: https://github.com/holzgeist/flutter_inappwebview
      path: flutter_inappwebview_android
      ref: d89b1d32638b49dfc58c4b7c84153be0c269d057


flutter_icons:
  android: true
  ios: true
  adaptive_icon_foreground: "assets/image/png/Logo.png"
  adaptive_icon_background: "assets/image/png/Logo.png"  # Same as foreground
  adaptive_icon_maskable: true
  image_path: "assets/image/png/Logo.png"




flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/image/flags/
    - assets/image/png/
    - assets/image/svg/
    - assets/image/json/
    - assets/

  fonts:
    - family: Vazir-Bold
      fonts:
        - asset: assets/font/vazir-bold.ttf
    - family: Tajawal-Medium
      fonts:
        - asset: assets/font/Tajawal-Medium.ttf

    